baseurl = "//jwsonic.github.io/"
languageCode = "en-us"
title = "John Palgut"
theme = "purehugo"
watch=false

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  description = "Coder. Gamer. Husband."
  twitterName = "jwsonic"
  githubName = "Jwsonic"
